services:
    webapp:
        image: ghcr.io/jovandrobnjak/devops-training-docker-nodejs-sample:v1.1.0
        ports:
            - '3000:80'
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DATABASE: 'todo'
            POSTGRES_USER: 'postgres'
            POSTGRES_PORT: 5432
            POSTGRES_HOST: 'db'
    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DATABASE: 'todo'
            POSTGRES_USER: 'postgres'
