apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.label }}
data:
    POSTGRES_HOST: {{ .Values.configmap.host }}
    POSTGRES_PORT: "{{ .Values.configmap.port }}"