apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label }}-webapp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: {{ .Values.app.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: {{ .Values.label }}-webapp
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.label }}-configmap

