name: Create and publish a Docker image

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Verison for manual trigger'
                required: true
                type: string
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    IMAGE_TAG: ${{github.event_name == 'push' && github.ref_name || inputs.version}}
    AWS_REGION: eu-central-1
    AWS_ECR_REPOSITORY: jovand-private-ecr
    CLUSTER_NAME: jovand-cluster
    RELEASE_NAME: jovand-todo-app

jobs:
    test-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
            - run: npm install
            - run: npm test

    build-and-push-image:
        needs: test-app
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{env.AWS_REGION}}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  registries: ${{ secrets.AWS_ACCOUNT_ID }}
                  mask-password: 'true'

            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.IMAGE_TAG}}
                      ${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_REPOSITORY }}:docker-${{env.IMAGE_TAG}}

            - name: kubeconfig
              run: |
                  aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}  --kubeconfig ./kubeconfig
                  echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
                  echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
                  echo 'EOF' >> $GITHUB_ENV

            - name: Update EKS deployment with new image
              uses: koslib/helm-eks-action@v1.29.0
              env:
                  KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
              with:
                  command: helm upgrade --reuse-values --set "app.tag"="docker-${{ env.IMAGE_TAG }}" --namespace vegait-training ${{env.RELEASE_NAME}} oci://${{ steps.login-ecr.outputs.registry}}/${{ env.AWS_ECR_REPOSITORY }}
